[project]
name = "netauto_f5_lib"
version = "0.1.0"
description = "Internal library for NetAuto F5 orchestrator"
authors = [{ name = "Your Name", email = "your@email.com" }]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
