version: '3.8'

services:
  prefect-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - infrahub_default

  prefect-server:
    image: prefecthq/prefect:3-latest
    restart: always
    command: prefect server start
    ports:
      - "4200:4200"
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@prefect-db:5432/prefect
    depends_on:
      - prefect-db
    # networks:
    #   - infrahub_default

  # prefect-worker:
  #   image: prefecthq/prefect:3-latest
  #   command: prefect worker start --pool default --work-queue default --type process
  #   environment:
  #     PREFECT_API_URL: http://prefect-server:4200/api
  #     PYTHONPATH: /app
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./flows:/app/flows
  #   depends_on:
  #     - prefect-server
  #   restart: always
  #   # networks:
  #   #   - infrahub_default

  webhook-api:
    build:
      context: .
      dockerfile: webhook/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./webhook:/app/webhook
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PYTHONPATH: /app
    depends_on:
      - prefect-server
    # networks:
    #   - infrahub_default

volumes:
  postgres_data: {}

# networks:
#   infrahub_default:
#     external: true
